### PR TITLE
Make Travis execute our tests

### PR DESCRIPTION
**Pull request by mammuth**
Okay, I started getting something up:
We use Tox to run flake8 checks and run the testsuite defined in the setup.py.

Travis will run 10 jobs for a couple of Python, Django and django-cms versions, namely:
- `py{34,27}-latest`
- `py{34,27}-dj18-cms{34,33}`
- `py{34,27}-dj19-cms{34,33}`

Example Build: https://travis-ci.org/mammuth/djangocms-layouter/builds/247570051

This setup is based on django-cms plugins by Divio.

ToDo:
- Currently the CI won't run `makemigrations`, so it may fail when we don't checkin migrations in the branch of the PR. 
- Squash commits before merging (there are a couple of test-commits I used to test the Travis integration in my fork)

Related issue #21

### CODE REVIEW

**Comment by SteinRobert** [comment]
Hey @mammuth, I will have a look at it! Pretty cool, thanks for your contribution! 
I think it's fine if the CI breaks in case of missing migrations - because missing migrations aren't good ;) However squashing the commits would be great.

**Comment by mammuth** [comment]
GitHub allows to squash the commits when merging the PR :+1: :wink:

**Comment by mammuth** [comment]
We should add the missing migrations and test whether the CI build succeeds before merging it I guess.

**Comment by SteinRobert** [comment]
Even though I merged the migrations into the branch it seems like the CI does not pass.

**Comment by mammuth** [comment]
The tests run successfully! :tada:
But there is an error with the test coverage, I can check this out tomorrow.

**Comment by mammuth** [comment]
Travis builds are running successfully now. Ping @DanielPollithy

**Pull request merged**
